FROM python:3

ARG BRANCH
RUN git clone --single-branch -b $BRANCH https://github.com/IntegrCiTy/zerobnl.git

RUN pip install --upgrade pip

RUN cd zerobnl && pip install --no-cache-dir -r requirements.txt
RUN cd zerobnl && pip install .

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1
ENTRYPOINT ["python"]