FROM python:3

RUN pip install --upgrade pip

ARG branch=feature_save_tables
RUN git clone --single-branch -b $branch https://github.com/IntegrCiTy/zerobnl.git

RUN cd zerobnl && pip install --no-cache-dir -r requirements.txt
RUN cd zerobnl && python setup.py install

RUN pip install pandapower

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1
ENTRYPOINT ["python"]
